Add proliant xl420g9
Comcast/fishymetrics pull request #35
Opened 2024-03-06 03:40 UTC by ibrahimkk-moideen

Adding support for HP Proliant XL420 Server model #33 

**Test results:**
```
# HELP up Was the last scrape of chassis monitor successful.
# TYPE up gauge
up 1
# HELP xl420_memory_status Current memory status 1 = OK, 0 = BAD
# TYPE xl420_memory_status gauge
xl420_memory_status{totalSystemMemoryGiB="128"} 1
# HELP xl420_physical_drive_status Current physical drive status 1 = OK, 0 = BAD, -1 = DISABLED
# TYPE xl420_physical_drive_status gauge
xl420_physical_drive_status{id="16",location="Redacted",name="HpSmartStorageDiskDrive",serialnumber="Redacted"} 1
xl420_physical_drive_status{id="16",location="Redacted",name="HpSmartStorageDiskDrive",serialnumber="Redacted"} 1
[***output truncated***]
xl420_physical_drive_status{id="27",location="Redacted",name="HpSmartStorageDiskDrive",serialnumber="Redacted"} 1
xl420_physical_drive_status{id="27",location="Redacted",name="HpSmartStorageDiskDrive",serialnumber="Redacted"} 1
# HELP xl420_power_supply_output Power supply output in watts
# TYPE xl420_power_supply_output gauge
xl420_power_supply_output{memberId="1",sparePartNumber="754381-001"} 172
xl420_power_supply_output{memberId="2",sparePartNumber="754381-001"} 238
# HELP xl420_power_supply_status Current power supply status 1 = OK, 0 = BAD
# TYPE xl420_power_supply_status gauge
xl420_power_supply_status{memberId="1",sparePartNumber="754381-001"} 1
xl420_power_supply_status{memberId="2",sparePartNumber="754381-001"} 1
# HELP xl420_power_supply_total_capacity Total output capacity of all the power supplies
# TYPE xl420_power_supply_total_capacity gauge
xl420_power_supply_total_capacity{memberId="0"} 1600
# HELP xl420_power_supply_total_consumed Total output of all power supplies in watts
# TYPE xl420_power_supply_total_consumed gauge
xl420_power_supply_total_consumed{memberId="0"} 410
# HELP xl420_thermal_fan_speed Current fan speed in the unit of percentage, possible values are 0 - 100
# TYPE xl420_thermal_fan_speed gauge
xl420_thermal_fan_speed{name="Fan 1"} 39
xl420_thermal_fan_speed{name="Fan 10"} 51
xl420_thermal_fan_speed{name="Fan 2"} 64
xl420_thermal_fan_speed{name="Fan 3"} 64
xl420_thermal_fan_speed{name="Fan 4"} 61
xl420_thermal_fan_speed{name="Fan 5"} 51
xl420_thermal_fan_speed{name="Fan 6"} 39
xl420_thermal_fan_speed{name="Fan 7"} 64
xl420_thermal_fan_speed{name="Fan 8"} 64
xl420_thermal_fan_speed{name="Fan 9"} 61
# HELP xl420_thermal_fan_status Current fan status 1 = OK, 0 = BAD
# TYPE xl420_thermal_fan_status gauge
xl420_thermal_fan_status{name="Fan 1"} 1
xl420_thermal_fan_status{name="Fan 10"} 1
xl420_thermal_fan_status{name="Fan 2"} 1
xl420_thermal_fan_status{name="Fan 3"} 1
xl420_thermal_fan_status{name="Fan 4"} 1
xl420_thermal_fan_status{name="Fan 5"} 1
xl420_thermal_fan_status{name="Fan 6"} 1
xl420_thermal_fan_status{name="Fan 7"} 1
xl420_thermal_fan_status{name="Fan 8"} 1
xl420_thermal_fan_status{name="Fan 9"} 1
# HELP xl420_thermal_sensor_status Current sensor status 1 = OK, 0 = BAD
# TYPE xl420_thermal_sensor_status gauge
xl420_thermal_sensor_status{name="01-Front Ambient"} 1
xl420_thermal_sensor_status{name="02-CPU 1"} 1
[***output truncated***]
xl420_thermal_sensor_status{name="46-HD Board"} 1
xl420_thermal_sensor_status{name="48-HD Board"} 1
# HELP xl420_thermal_sensor_temperature Current sensor temperature reading in Celsius
# TYPE xl420_thermal_sensor_temperature gauge
xl420_thermal_sensor_temperature{name="01-Front Ambient"} 19
xl420_thermal_sensor_temperature{name="02-CPU 1"} 40
[***output truncated***]
xl420_thermal_sensor_temperature{name="46-HD Board"} 32
xl420_thermal_sensor_temperature{name="48-HD Board"} 29
```

Adding support for HP DL360 Redfish responses from iLO4. #34 

**Test results:**
```
# HELP dl360_disk_drive_status Current Disk Drive status 1 = OK, 0 = BAD
# TYPE dl360_disk_drive_status gauge
dl360_disk_drive_status{Id="0",location="Redacted",name="HpSmartStorageDiskDrive"} 1
dl360_disk_drive_status{Id="1",location="Redacted",name="HpSmartStorageDiskDrive"} 1
dl360_disk_drive_status{Id="2",location="Redacted",name="HpSmartStorageDiskDrive"} 1
dl360_disk_drive_status{Id="3",location="Redacted",name="HpSmartStorageDiskDrive"} 1
dl360_disk_drive_status{Id="4",location="Redacted",name="HpSmartStorageDiskDrive"} 1
dl360_disk_drive_status{Id="5",location="Redacted",name="HpSmartStorageDiskDrive"} 1
dl360_disk_drive_status{Id="6",location="Redacted",name="HpSmartStorageDiskDrive"} 1
dl360_disk_drive_status{Id="7",location="Redacted",name="HpSmartStorageDiskDrive"} 1
# HELP dl360_logical_drive_raid Current Logical Drive Raid
# TYPE dl360_logical_drive_raid gauge
dl360_logical_drive_raid{logicaldrivename="Redacted",name="HpSmartStorageLogicalDrive",raid="0",volumeuniqueidentifier="Redacted"} 1
# HELP dl360_power_supply_output Power supply output in watts
# TYPE dl360_power_supply_output gauge
dl360_power_supply_output{memberId="1",sparePartNumber="754377-001"} 116
dl360_power_supply_output{memberId="2",sparePartNumber="754377-001"} 0
# HELP dl360_power_supply_status Current power supply status 1 = OK, 0 = BAD
# TYPE dl360_power_supply_status gauge
dl360_power_supply_status{memberId="1",sparePartNumber="754377-001"} 1
dl360_power_supply_status{memberId="2",sparePartNumber="754377-001"} 1
# HELP dl360_power_supply_total_capacity Total output capacity of all the power supplies
# TYPE dl360_power_supply_total_capacity gauge
dl360_power_supply_total_capacity{memberId="0"} 500
# HELP dl360_power_supply_total_consumed Total output of all power supplies in watts
# TYPE dl360_power_supply_total_consumed gauge
dl360_power_supply_total_consumed{memberId="0"} 116
# HELP dl360_thermal_fan_speed Current fan speed in the unit of percentage, possible values are 0 - 100
# TYPE dl360_thermal_fan_speed gauge
dl360_thermal_fan_speed{name="Fan 1"} 19
dl360_thermal_fan_speed{name="Fan 2"} 15
dl360_thermal_fan_speed{name="Fan 3"} 19
dl360_thermal_fan_speed{name="Fan 4"} 19
dl360_thermal_fan_speed{name="Fan 5"} 21
dl360_thermal_fan_speed{name="Fan 6"} 27
dl360_thermal_fan_speed{name="Fan 7"} 27
# HELP dl360_thermal_fan_status Current fan status 1 = OK, 0 = BAD
# TYPE dl360_thermal_fan_status gauge
dl360_thermal_fan_status{name="Fan 1"} 1
dl360_thermal_fan_status{name="Fan 2"} 1
dl360_thermal_fan_status{name="Fan 3"} 1
dl360_thermal_fan_status{name="Fan 4"} 1
dl360_thermal_fan_status{name="Fan 5"} 1
dl360_thermal_fan_status{name="Fan 6"} 1
dl360_thermal_fan_status{name="Fan 7"} 1
```

2024-03-06 15:05 UTC, derrick-dacosta requested changes

2024-03-07 15:48 UTC, ibrahimkk-moideen commented on hpe/dl360/power.go
>  	Hpe Hpe `json:"Hpe"`
Updated in [802c769](https://github.com/Comcast/fishymetrics/pull/35/commits/802c76924269b508d053d8692fa519cb3d124d60).

2024-03-07 15:49 UTC, ibrahimkk-moideen commented on hpe/xl420/drive.go
> +	}
Updated in [802c769](https://github.com/Comcast/fishymetrics/pull/35/commits/802c76924269b508d053d8692fa519cb3d124d60).

2024-03-07 15:49 UTC, ibrahimkk-moideen commented on hpe/dl360/exporter.go
> +			} else {
Updated in [802c769](https://github.com/Comcast/fishymetrics/pull/35/commits/802c76924269b508d053d8692fa519cb3d124d60).

2024-03-07 15:49 UTC, ibrahimkk-moideen commented on hpe/dl360/exporter.go
> +			} else {
Updated in [802c769](https://github.com/Comcast/fishymetrics/pull/35/commits/802c76924269b508d053d8692fa519cb3d124d60).

2024-03-07 15:49 UTC, ibrahimkk-moideen commented on hpe/xl420/exporter.go
> +			if getController.Links.LogicalDrives.URL != "" {
Updated in [802c769](https://github.com/Comcast/fishymetrics/pull/35/commits/802c76924269b508d053d8692fa519cb3d124d60).

2024-03-07 15:49 UTC, ibrahimkk-moideen commented on hpe/xl420/exporter.go
> +			if getController.Links.PhysicalDrives.URL != "" {
Updated in [802c769](https://github.com/Comcast/fishymetrics/pull/35/commits/802c76924269b508d053d8692fa519cb3d124d60).

2024-03-07 23:03 UTC, derrick-dacosta approved these changes
LGTM!

2024-03-08 02:37 UTC, merged